# the third version of docker compose yaml syntax
version: '3'
services:
    nodejs_app:
      # relative directory to docker compose file:
      build: ./app
      volumes:
        - ./app:/usr/src/app
      ports:
        - 8088:8080
      tty: true # show colors in logs https://github.com/docker/compose/issues/2231#issuecomment-165137408

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5433:5432

    adminer:
      image: adminer
      restart: always
      ports:
        - 8089:8080